### ISSUE TITLE
Add to docs wiki DoD and DoR

### ISSUE THREAD

**Issue by frle10** [vs-labs/distributed-task-scheduler#8]

**Comment by frle10** [comment]
@dominikvrbic Here is the link to the DoR and DoD page in the wiki. Can you please review it and see if there is anything to add or change? Not sure about some things since we didn't define this together.

https://github.com/vs-labs/distributed-task-scheduler/wiki/DoR-&-DoD

**Comment by dominikvrbic** [comment]
looks good
